stages:
  - test
  - docker
  - update-config
  - deploy
  - production_test

variables:
  IMAGE_NAME: $DOCKER_USERNAME/elwasya
  APP_VERSION: $CI_PIPELINE_IID
  S3_BUCKET: ahmeddwieb-wasaya-media
  AWS_REGION: eu-west-1
#todo add test stage

docker-build:
  stage: docker
  image: docker:24

  services:
    - docker:dind

  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t $IMAGE_NAME:$APP_VERSION .
    - docker push $IMAGE_NAME:$APP_VERSION
    - docker tag "$IMAGE_NAME:$APP_VERSION" "$IMAGE_NAME:latest"
    - docker push "$IMAGE_NAME:latest"
    
update-config:
  stage: update-config
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
    - aws s3 cp docker-compose.prod.yml "s3://${S3_BUCKET}/docker-compose.yml"

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
    - |
      aws autoscaling describe-auto-scaling-groups \
        --auto-scaling-group-names wasaya-asg \
        --query 'AutoScalingGroups[0].Instances[].InstanceId' \
        --output text > instance_ids.txt
    - cat instance_ids.txt
    - |
      aws ssm send-command \
        --instance-ids $(cat instance_ids.txt) \
        --document-name "AWS-RunShellScript" \
        --parameters '{"commands":["cd /opt/wasaya", "docker compose pull backend", "docker compose up -d backend"]}' \
        --region "$AWS_REGION"
production_test:
  stage: production_test
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - sleep 300
    - curl -fail http://api.ahmeddwieb.me/health/db
    - curl -fail http://api.ahmeddwieb.me/health
    - curl -fail http://api.ahmeddwieb.me/docs