stages:
  - test
  - docker
  - update-config
  - deploy
  - production_test

variables:
  IMAGE_NAME: $DOCKER_USERNAME/elwasya
  APP_VERSION: $CI_PIPELINE_IID
  S3_BUCKET: ahmeddwieb-wasaya-media
  AWS_REGION: eu-west-1
#todo add test stage

docker-build:
  stage: docker
  image: docker:24

  services:
    - docker:dind

  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t $IMAGE_NAME:$APP_VERSION .
    - docker push $IMAGE_NAME:$APP_VERSION

update-config:
  stage: update-config
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
  - sed "s|__IMAGE__|${IMAGE_NAME}:${APP_VERSION}|g" docker-compose.yml > docker-compose.production.yml
  - cat docker-compose.production.yml
  - aws s3 cp docker-compose.production.yml "s3://${S3_BUCKET}/docker-compose.yml"

refresh_ASG:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
  - |
    aws autoscaling start-instance-refresh \
      --auto-scaling-group-name wasaya-asg \
      --preferences "MinHealthyPercentage=50,InstanceWarmup=300"

production_test:
  stage: production_test
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - sleep 250
    - curl -fail http://api.ahmeddwieb.me/health/db
    - curl -fail http://api.ahmeddwieb.me/health
    - curl -fail http://api.ahmeddwieb.me/docs