#1 backend
#depend on db (health check)
#2 db
# TODO
#3 front end
#depend on db and backend (health check)
#4 nginx
#5 private network and public
#6 volume to backend and db
services:
  backend:
    image: ${IMAGE_NAME}:${APP_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpassword@db:3306/wasaya
      - BACKEND_BASE_URL=http://localhost:8000
    depends_on:
       db:
         condition: service_healthy
    networks:
      - backend-net
  db:
    image: "mysql:8.4.5"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wasaya
    ports:
      - target: 3306
        published: 3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend-net
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  backend-net:
    name: elwasya_backend-net
    driver: bridge

volumes:
  mysql-data:
