services:
  backend:
    image: __IMAGE__
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpassword@${RDS_HOSTNAME}:3306/wasaya
