---

- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker repository
  apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: check if docker run
  command: docker --version
- name: Create app directory
  file:
    path: /opt/wasaya
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: copy docker compose
  copy:
    src: docker-compose.yml
    dest: /opt/wasaya/docker-compose.yml
    owner: root
    group: root
    mode: '0644'


#Nginx
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: copy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Create ssl directory

  file:
      path: /etc/nginx/ssl
      state: directory
      mode: "0755"

- name: copy cert
  copy:
    src: wasaya.crt
    dest: /etc/nginx/ssl/wasaya.crt
    owner: root
    group: root
    mode: '0644'

- name: copy private key
  copy:
    src: wasaya.key
    dest: /etc/nginx/ssl/wasaya.key
    owner: root
    group: root
    mode: '0644'

- name: reload nginx
  service:
    name: nginx
    state: reloaded

#sudo fallocate -l 1G /swapfile
#ubuntu@ip-10-0-1-220:/opt/wasaya$ sudo chmod 600 /swapfile
#ubuntu@ip-10-0-1-220:/opt/wasaya$ sudo mkswap /swapfile
#Setting up swapspace version 1, size = 1024 MiB (1073737728 bytes)
#no label, UUID=1bc8b7c2-b1b3-4dca-ab35-e6b033e379f1
#ubuntu@ip-10-0-1-220:/opt/wasaya$ sudo swapon /swapfile
#ubuntu@ip-10-0-1-220:/opt/wasaya$ free -h
#               total        used        free      shared  buff/cache   available
#Mem:           908Mi       825Mi        57Mi       2.8Mi       135Mi        83Mi
#Swap:          1.0Gi        57Mi       966Mi
#ubuntu@ip-10-0-1-220:/opt/wasaya$ echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
#/swapfile none swap sw 0 0
#ubuntu@ip-10-0-1-220:/opt/wasaya$ cat /etc/fstab
#LABEL=cloudimg-rootfs	/	 ext4	discard,commit=30,errors=remount-ro	0 1
#LABEL=BOOT	/boot	ext4	defaults	0 2
#LABEL=UEFI	/boot/efi	vfat	umask=0077	0 1
#/swapfile none swap sw 0 0
