apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  SECRET_KEY: N2YyZDkyZTAzYjdmZjBkMDUyZWRjNDBjNTFkNmE2ODM0NDdmY2ViZWNhNzVmZDIzZGE4ZjUxMDA2MjMxMjMxYg==
  DATABASE_URL: bXlzcWwrcHlteXNxbDovL3Jvb3Q6cm9vdHBhc3N3b3JkQGxvY2FsaG9zdDozMzA2L3dhc2F5YQ==
