apiVersion: v1
kind: Service
metadata:
  name: backend-service                    # this name IS the DNS hostname other pods use
spec:
  type: NodePort
  selector:
    app: wasaya                   # picks up pods with this label — no manual wiring
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080