"""add checkin active

Revision ID: 4099236d096f
Revises: 466acc24199a
Create Date: 2026-09-05 19:35:21.850032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4099236d096f'
down_revision = '466acc24199a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('checkin_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'checkin_active')
    # ### end Alembic commands ###