"""remove timezone from user

Revision ID: e08d9329203d
Revises: 4099236d096f
Create Date: 2026-09-09 16:47:28.995515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e08d9329203d'
down_revision = '4099236d096f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False))
    # ### end Alembic commands ###