server {
    listen 443 ssl http2;
    server_name wasaya.ahmeddwieb.me;
    ssl_certificate /etc/nginx/ssl/wasaya.crt;
    ssl_certificate_key /etc/nginx/ssl/wasaya.key;
    location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
server {
    listen 80;
    server_name wasaya.ahmeddwieb.me;
    return 301 https://$server_name$request_uri;
}